### ISSUE TITLE
oslo_config.cfg.RequiredOptError for torrent_path

### ISSUE THREAD

**Issue by huangsam** [shad7/seedbox#32]
Currently using Python 3.6 with virtualenv.

I got `seedmgr --config-file ./etc/seedbox/seedbox.conf` to work from the base directory of the Git repository.

When running `dbadmin passwd --password s3cret`, I'm running into the following error:

```
/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/sandman/__init__.py:8: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy import SQLAlchemy
/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/sandman/__init__.py:9: ExtDeprecationWarning: Importing flask.ext.httpauth is deprecated, use flask_httpauth instead.
  from flask.ext.httpauth import HTTPBasicAuth
/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:819: UserWarning: SQLALCHEMY_DATABASE_URI not set. Defaulting to "sqlite:///:memory:".
  'SQLALCHEMY_DATABASE_URI not set. Defaulting to '
/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/sandman/model/utils.py:6: ExtDeprecationWarning: Importing flask.ext.admin is deprecated, use flask_admin instead.
  from flask.ext.admin import Admin
Traceback (most recent call last):
  File "/Users/samhuang/.virtualenvs/seedbox/bin/dbadmin", line 10, in <module>
    sys.exit(cli())
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/seedbox/db/admin.py", line 53, in save_password
    with open(load_passfile(), 'w') as fd:
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/seedbox/db/admin.py", line 20, in load_passfile
    service.prepare_service([])
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/seedbox/service.py", line 92, in prepare_service
    _configure(args)
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/seedbox/service.py", line 81, in _configure
    config_files)))
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/oslo_config/cfg.py", line 2471, in __call__
    self._check_required_opts()
  File "/Users/samhuang/.virtualenvs/seedbox/lib/python3.6/site-packages/oslo_config/cfg.py", line 3129, in _check_required_opts
    raise RequiredOptError(opt.name, group)
oslo_config.cfg.RequiredOptError: value required for option torrent_path in group [torrent]
```

I'm trying to find a way to specify the configuration file in `dbadmin`, but it appears that I cannot. I also tried to copy my customized `seedbox.conf` to `~/seedbox/etc/seedbox/seedbox.conf` and still cannot get this to work.

**Comment by shad7** [comment]
If you copied the file to `~/seedbox/etc/seedbox/seedbox.conf`, then it will be picked up automatically.

Does your file have the section `[torrent]` with a value for `torrent_path` ?

**Comment by huangsam** [comment]
Yes these were my configuration values for `[torrent]`

```
[torrent]

# Location of the .torrent files (string value)
torrent_path = /home/samhuang/.config/state

# Location(s) of the media files (list value)
media_paths = $base_client_path/completed

# Location of the downloading torrents (string value)
incomplete_path = $base_client_path/inprogress

# List of video filetypes to support. (ignore others) (list value)
#video_filetypes = .avi,.mp4,.mkv,.mpg

# List of compressed filetypes to support. (ignore others) (list
# value)
#compressed_filetypes = .rar

# Minimum file size of a media file (integer value)
#minimum_file_size = 75000000
```

**Comment by huangsam** [comment]
Is there something else that could go wrong with the above configuration?
